version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
  backend:
    image: vasiliyyakovlev/kittygram_backend
    env_file: .env
    volumes:
      - static:/static
      - media:/backend/media
    depends_on:
      - db
  frontend:
    env_file: .env
    image: vasiliyyakovlev/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: vasiliyyakovlev/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend